---
title: 'Group 3: Final Analysis'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(EloRating)
```

### Calculating Elo Score

The following code segment provided by the client will calculate the elo ratings of cows.

#### Sampling replacements
```{r elo score feed, message=TRUE}
# setting up
all_replacement_THI <- read.csv('../data/replacement_with_THI.csv')
water <- all_replacement_THI %>% filter(Bin_type == 'Water')
feed <- all_replacement_THI %>% filter(Bin_type == 'Feed')
THI_threshold <- 65
water_high <- all_replacement_THI %>% filter(Bin_type == 'Water', THI_max>=THI_threshold)
water_low <- all_replacement_THI %>% filter(Bin_type == 'Water', THI_max<THI_threshold)
feed_high <- all_replacement_THI %>% filter(Bin_type == 'Feed', THI_max>=THI_threshold)
feed_low <- all_replacement_THI %>% filter(Bin_type == 'Feed', THI_max<THI_threshold)

water_cows <- unique(water$Reactor_cow,water$Actor_cow)
feed_cows <- unique(feed$Reactor_cow,feed$Actor_cow)
intersection <- Reduce(intersect, list(water_cows,feed_cows))

# filtering 
water_high_cows <- unique(water_high$Reactor_cow,water_high$Actor_cow)
water_low_cows <- unique(water_low$Reactor_cow,water_low$Actor_cow)
feed_high_cows <- unique(feed_high$Reactor_cow,feed_high$Actor_cow)
feed_low_cows <-unique(feed_low$Reactor_cow,feed_low$Actor_cow)
sub_intersection <- Reduce(intersect, list(water_high_cows, water_low_cows, feed_high_cows, feed_low_cows))

water <- water %>%
  filter(Actor_cow %in% intersection & Reactor_cow %in% intersection)

feed <- feed %>%
  filter(Actor_cow %in% intersection & Reactor_cow %in% intersection)

water_high <- water_high %>%
  filter(Actor_cow %in% sub_intersection & Reactor_cow %in% sub_intersection)

water_low <- water_low %>%
  filter(Actor_cow %in% sub_intersection & Reactor_cow %in% sub_intersection)

feed_high <- feed_high %>%
  filter(Actor_cow %in% sub_intersection & Reactor_cow %in% sub_intersection)

feed_low <- feed_low %>%
  filter(Actor_cow %in% sub_intersection & Reactor_cow %in% sub_intersection)
```

### Repeat the same process (num) times 
```{r elo loop, message=TRUE}
water_feed_cor = 0;
water_feed_high_cor = 0;
water_feed_low_cor = 0;
water_high_low_cor = 0;
feed_high_low_cor = 0;
num <- 10
for (i in 1:num) {
  # -----------------------------------------* Test 1 *-----------------------------------------
  # ----------------------------------------- feed bins overall -----------------------------------------
  sub_repl <- feed[sample(1:nrow(water)),]
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores
  elo_res_feed=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- water bins overall -----------------------------------------
  sub_repl <- water
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores 
  elo_res_water = elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- calculate feed vs water correlation -----------------------------------------
  last_elo_water <- extract_elo(elo_res_water)
  last_elo_feed <- extract_elo(elo_res_feed)
  cows <- Reduce(intersect, list(names(last_elo_water),names(last_elo_feed)))
  sorted_last_elo_feed <- last_elo_feed[sort(cows)]
  sorted_last_elo_water <- last_elo_water[sort(cows)]
  water_feed_cor <- water_feed_cor + cor.test(x=unname(sorted_last_elo_water), y=unname(sorted_last_elo_feed), method = 'spearman')$estimate
  
  # -----------------------------------------* Test 2 *-----------------------------------------
  # ----------------------------------------- feed bins high THI -----------------------------------------
  sub_repl <- feed_high[sample(1:nrow(water_high)),]
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores
  elo_res_feed_high_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)

  # ----------------------------------------- water bins high THI -----------------------------------------
  sub_repl <- water_high
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores 
  elo_res_water_high_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- calculate feed high THI vs water high THI correlation -----------------------------------------
  last_elo_water_high_THI <- extract_elo(elo_res_water_high_THI)
  last_elo_feed_high_THI <- extract_elo(elo_res_feed_high_THI)
  high_THI_cows <- Reduce(intersect, list(names(last_elo_water_high_THI),names(last_elo_feed_high_THI)))
  sorted_last_elo_feed_high_THI <- last_elo_feed_high_THI[sort(high_THI_cows)]
  sorted_last_elo_water_high_THI <- last_elo_water_high_THI[sort(high_THI_cows)]
  water_feed_high_cor <- water_feed_high_cor + cor.test(x=unname(sorted_last_elo_feed_high_THI), y=unname(sorted_last_elo_water_high_THI), method = 'spearman')$estimate
  
  # -----------------------------------------* Test 3 *-----------------------------------------
  # ----------------------------------------- feed bins low THI -----------------------------------------
  sub_repl <- feed_low[sample(1:nrow(water_low)),]
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores
  elo_res_feed_low_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- water bins low THI -----------------------------------------
  sub_repl <- water_low
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores 
  elo_res_water_low_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- calculate feed low THI vs water low THI correlation -----------------------------------------
  last_elo_water_low_THI <- extract_elo(elo_res_water_low_THI)
  last_elo_feed_low_THI <- extract_elo(elo_res_feed_low_THI)
  low_THI_cows <- Reduce(intersect, list(names(last_elo_water_low_THI),names(last_elo_feed_low_THI)))
  sorted_last_elo_feed_low_THI <- last_elo_feed_low_THI[sort(low_THI_cows)]
  sorted_last_elo_water_low_THI <- last_elo_water_low_THI[sort(low_THI_cows)]
  water_feed_low_cor <- water_feed_low_cor + cor.test(x=unname(sorted_last_elo_feed_low_THI), y=unname(sorted_last_elo_water_low_THI), method = 'spearman')$estimate
  
  # -----------------------------------------* Test 4 *-----------------------------------------
  # ----------------------------------------- water bins high THI -----------------------------------------
  sub_repl <- water_high
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores 
  elo_res_water_high_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- water bins low THI -----------------------------------------
  sub_repl <- water_low[sample(1:nrow(water_high)),]
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores 
  elo_res_water_low_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- calculate water high THI vs low THI correlation -----------------------------------------
  last_elo_water_low_THI <- extract_elo(elo_res_water_low_THI)
  last_elo_water_high_THI <- extract_elo(elo_res_water_high_THI)
  water_cows <- Reduce(intersect, list(names(last_elo_water_low_THI),names(last_elo_water_high_THI)))
   water_high_low_cor <- water_high_low_cor + cor.test(x=unname(last_elo_water_low_THI[sort(water_cows)]), y=unname(last_elo_water_high_THI[sort(water_cows)]), method = 'spearman')$estimate
  
  # -----------------------------------------* Test 5 *-----------------------------------------
  # ----------------------------------------- feed bins high THI -----------------------------------------
  sub_repl <- feed_high
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores
  elo_res_feed_high_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- feed bins low THI -----------------------------------------
  sub_repl <- feed_low[sample(1:nrow(feed_high)),]
  sub_repl$index <- seq(1, nrow(sub_repl))
  ## Order replacements
  elo_repl_list <- sub_repl[order(sub_repl$hour),c("Actor_cow", "Reactor_cow","hour", "Bin", "date")]
  colnames(elo_repl_list)=c("winner","loser","time","bin", "date")
  elo_repl_list$index <- seq(1, nrow(elo_repl_list))
  #Calculate the ELO scores
  elo_res_feed_low_THI=elo.seq(winner=as.character(elo_repl_list$winner),
                             loser=as.character(elo_repl_list$loser),
                             Date=elo_repl_list$date,
                             k=20,
                             #presence=presence_comb,
                             runcheck = F,
                             progressbar=T)
  
  # ----------------------------------------- calculate feed high THI vs low THI correlation -----------------------------------------
  last_elo_feed_low_THI <- extract_elo(elo_res_feed_low_THI)
  last_elo_feed_high_THI <- extract_elo(elo_res_feed_high_THI)
  feed_cows <- Reduce(intersect, list(names(last_elo_feed_low_THI),names(last_elo_feed_high_THI)))
  feed_high_low_cor <- feed_high_low_cor + cor.test(x=unname(last_elo_feed_low_THI[sort(feed_cows)]), y=unname(last_elo_feed_high_THI[sort(feed_cows)]), method = 'spearman')$estimate
}

# compute average correlation
feed_water_cor <- water_feed_cor/num
final_water_feed_high_cor <- water_feed_high_cor/num
final_water_feed_low_cor <- water_feed_low_cor/num
final_water_high_low_cor <- water_high_low_cor/num
final_feed_high_low_cor <- feed_high_low_cor/num
```

### Calculate fisher's z transformation score
```{r fisher-z-transformation, message=TRUE}
# -----Test 2 final_water_feed_high_cor & 3 final_water_feed_low_cor ------
library(DescTools)
# ------ COMPARING BETWEEN TEST 2 RHO VS. TEST 3 RHO -----------
n1 <- length(sorted_last_elo_feed_high_THI) + length(sorted_last_elo_water_high_THI)
n2 <- length(sorted_last_elo_feed_low_THI) + length(sorted_last_elo_water_low_THI)
z_final_water_feed_high_cor <- FisherZ(final_water_feed_high_cor)
z_final_water_feed_low_cor <- FisherZ(final_water_feed_low_cor)
zobs_test23 <- (z_final_water_feed_high_cor-z_final_water_feed_low_cor) / sqrt( 1 / (n1-3) + 1 / (n2-3) )
pval_test23 <- 2 * pnorm(-abs(zobs_test23))
pval_test23


# -----Test 4 final_water_high_low_cor & 5 final_feed_high_low_cor ------

# ------ COMPARING BETWEEN TEST 4 RHO VS. TEST 5 RHO -----------
n1<- length(last_elo_water_low_THI[sort(water_cows)]) + length(last_elo_water_high_THI[sort(water_cows)])
n2 <- length(last_elo_feed_low_THI[sort(feed_cows)]) + length(last_elo_feed_high_THI[sort(feed_cows)])
z_final_water_high_low_cor <- FisherZ(final_water_high_low_cor)
z_final_feed_high_low_cor <- FisherZ(final_feed_high_low_cor)
zobs_test45 <- (z_final_water_high_low_cor-z_final_feed_high_low_cor) / sqrt( 1 / (n1-3) + 1 / (n2-3) )
pval_test45 <- 2 * pnorm(-abs(zobs_test45))
pval_test45
```

### Optimize k

```{r optimization, message=FALSE}
# elo_res_water <- readRDS('../data/elo_res_water.rds')
# elo_res_feed <- readRDS('../data/elo_res_feed.rds')
# elo_res_water_low_THI <- readRDS('../data/elo_res_water_low_THI.rds')
# elo_res_water_high_THI <- readRDS('../data/elo_res_water_high_THI.rds')
# elo_res_feed_low_THI <- readRDS('../data/elo_res_feed_low_THI.rds')
# elo_res_feed_high_THI <- readRDS('../data/elo_res_feed_high_THI.rds')

##optimize k
#ores_water <- optimizek(elo_res_water, krange = c(1, 100), resolution = 100)
#ores_water$best

#ores_feed <- optimizek(elo_res_feed, krange = c(1, 100), resolution = 100)
#ores_feed$best

# ores_water_low_THI <- optimizek(elo_res_water_low_THI, krange = c(1, 100), resolution = 100)
# ores_water_low_THI$best
# ores_water_high_THI <- optimizek(elo_res_water_high_THI, krange = c(1, 100), resolution = 100)
# ores_water_high_THI$best
# ores_feed_low_THI <- optimizek(elo_res_feed_low_THI, krange = c(1, 100), resolution = 100)
# ores_feed_low_THI$best
# ores_feed_high_THI <- optimizek(elo_res_feed_high_THI, krange = c(1, 100), resolution = 100)
# ores_feed_high_THI$best
```
